-- 3
SELECT * FROM  dbo.DONGXE WHERE SoChoNgoi > 5

-- 4
SELECT * FROM dbo.NHACUNGCAP WHERE MaNhaCC IN(
	(SELECT MaNhaCC FROM dbo.DangKyCC WHERE DongXe IN 
		(SELECT DongXe FROM dbo.DONGXE WHERE HangXe LIKE 'Toyota') AND MaMP IN
			(SELECT MaMP FROM dbo.MUCPHI WHERE DonGia = 15)
			)
	OR MaNhaCC IN(
		(SELECT MaNhaCC FROM dbo.DangKyCC WHERE DongXe IN 
		(SELECT DongXe FROM dbo.DONGXE WHERE HangXe LIKE 'Kia') AND MaMP IN
			(SELECT MaMP FROM dbo.MUCPHI WHERE DonGia = 20)
	)
);

SELECT DISTINCT b.* FROM dbo.DangKyCC a
INNER JOIN dbo.NHACUNGCAP b ON a.MaNhaCC = b.MaNhaCC
INNER JOIN dbo.MUCPHI c on a.MaMP = c.MaMP
INNER JOIN dbo.DONGXE d ON a.DongXe = d.DongXe
WHERE (d.HangXe LIKE 'Toyota' AND c.DonGia = 15)OR
	(d.HangXe LIKE 'KIA' AND c.DonGia = 20)