-- 3
SELECT * FROM  dbo.DONGXE WHERE SoChoNgoi > 5

-- 4
SELECT * FROM dbo.NHACUNGCAP WHERE MaNhaCC IN(
	(SELECT MaNhaCC FROM dbo.DangKyCC WHERE DongXe IN 
		(SELECT DongXe FROM dbo.DONGXE WHERE HangXe LIKE 'Toyota') AND MaMP IN
			(SELECT MaMP FROM dbo.MUCPHI WHERE DonGia = 15000)
			)
	OR MaNhaCC IN(
		(SELECT MaNhaCC FROM dbo.DangKyCC WHERE DongXe IN 
		(SELECT DongXe FROM dbo.DONGXE WHERE HangXe LIKE 'Kia') AND MaMP IN
			(SELECT MaMP FROM dbo.MUCPHI WHERE DonGia = 15000)
	)
);